CREATE TABLE EnrollmentInfo (
    ENROLLMENT_ID INT PRIMARY KEY,
    STU_ID INT NOT NULL,
    COURSE_ID INT NOT NULL,
    ENROLL_STATUS ENUM('Enrolled', 'Not Enrolled') NOT NULL,
    FOREIGN KEY (STU_ID) REFERENCES StudentInfo(STU_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES CoursesInfo(COURSE_ID)
);